/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import git.*;
import java.util.ArrayList;
import gitController.GitController;
/**
 *
 * @author centr
 */
public class GitAdd extends javax.swing.JFrame {
    Menu ventanaInicio = null;
    GitController controlador = new GitController();
    ArrayList<String> listaArchivos  = new ArrayList<String>();
    /**
     * Creates new form gitAdd
     */
    public GitAdd() {
        initComponents();
    }

    GitAdd(Menu aThis) {
        initComponents();
        errorTxt.setVisible(false);
        filesMSG.setVisible(false);
        fileListTxt.setVisible(false);
        aThis.setVisible(false);
        this.ventanaInicio = aThis;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        errorTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fileListTxt = new javax.swing.JLabel();
        filesMSG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        allBtn.setText("All");
        allBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBtnActionPerformed(evt);
            }
        });

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("gitAdd:");

        jLabel2.setText("Archivo:");

        addBtn.setText("Añadir");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        errorTxt.setText("Texto de Error");

        jLabel4.setText("Archivos Añadidos:");

        fileListTxt.setText("ListaArchivos");

        filesMSG.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(allBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(200, 200, 200)
                                    .addComponent(aceptarBtn)
                                    .addGap(172, 172, 172)
                                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(addBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(errorTxt))
                            .addComponent(fileListTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(filesMSG)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addGap(18, 18, 18)
                .addComponent(errorTxt)
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileListTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filesMSG)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allBtn)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelBtn))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        ventanaInicio.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void allBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBtnActionPerformed
        // TODO add your handling code here:
        ventanaInicio.gitRep.zonas.addAllToIndex();
        ventanaInicio.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_allBtnActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        // TODO add your handling code here:
        if(!listaArchivos.isEmpty()){
            ventanaInicio.gitRep.zonas.addToIndex(listaArchivos);
            ventanaInicio.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }else{
            filesMSG.setText("No se han seleccionado archivos");
            filesMSG.setVisible(true);
        }
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String archivo = jTextField1.getText();
        if(!archivo.isEmpty()){
            ArrayList<String> lista = controlador.getWorkNameList(ventanaInicio.gitRep.zonas.workspace);
            if(inList(archivo, lista)){
                if(!inList(archivo, listaArchivos )){
                    listaArchivos.add(archivo);
                    if(listaArchivos.size() == 1){
                        fileListTxt.setText(archivo);
                        fileListTxt.setVisible(true);
                        filesMSG.setVisible(false);
                    }else{
                        fileListTxt.setText(fileListTxt.getText()+", "+archivo); 
                    }
                    errorTxt.setVisible(false);
                }else{
                    errorTxt.setText("Error: El Archivo ya fue añadido.");
                    errorTxt.setVisible(true);
                }
            }else{
                errorTxt.setText("Error: El Archivo no se encuentra en el Workspace.");
                errorTxt.setVisible(true);
            }
        }else{
            errorTxt.setText("Error: El Archivo no puede tener el nombre vacio.");
            errorTxt.setVisible(true);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    public Boolean inList(String S, ArrayList<String> sL ){
        Boolean valor = false;
        for(int i = 0; i < sL.size(); i++){
            if(sL.get(i).equals(S)){
               valor = true;
            }
        }
        return valor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton allBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JLabel fileListTxt;
    private javax.swing.JLabel filesMSG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
