/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author centr
 */
public class GitCommit extends javax.swing.JFrame {
    Menu ventanaInicio = null;
    /**
     * Creates new form gitCommit
     */
    public GitCommit() {
        initComponents();
    }

    GitCommit(Menu aThis) {
        initComponents();
        String s = "";
        for(int i = 0; i< aThis.gitRep.zonas.index.list.FL.size();i++){
            if(i==0){
                s = s+ aThis.gitRep.zonas.index.list.FL.get(i).getName();
            }else{
                s = s +", "+ aThis.gitRep.zonas.index.list.FL.get(i).getName();
            }
        }
        s = s+ ".";
        FileBox.setText(s);
        errorTxt.setVisible(false);
        aThis.setVisible(false);
        this.ventanaInicio = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cncelBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CommentaryBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FileBox = new javax.swing.JTextArea();
        errorTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cncelBtn.setText("Cancelar");
        cncelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cncelBtnActionPerformed(evt);
            }
        });

        acceptBtn.setText("Aceptar");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Comentario:");

        jLabel2.setText("Archivos:");

        FileBox.setEditable(false);
        FileBox.setColumns(20);
        FileBox.setRows(5);
        jScrollPane1.setViewportView(FileBox);

        errorTxt.setText("Error: el comentario debe de tener al menos 3 carácteres.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(CommentaryBox, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptBtn)
                        .addGap(52, 52, 52)
                        .addComponent(cncelBtn)))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(errorTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cncelBtn)
                    .addComponent(acceptBtn))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        // TODO add your handling code here:
        String m = CommentaryBox.getText();
        if(m.length() > 3){
            ventanaInicio.gitRep.gitCommit(m);
            ventanaInicio.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }else{
            CommentaryBox.setText("");
            errorTxt.setVisible(true);
        }
        
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void cncelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cncelBtnActionPerformed
        // TODO add your handling code here:
        ventanaInicio.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cncelBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommentaryBox;
    private javax.swing.JTextArea FileBox;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton cncelBtn;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
